spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/car-rental}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    exception-logging: with_stacktrace
